spring:
  application.name: gateway
  sleuth:
    enabled: true
  zipkin:
    base-url: http://192.168.99.100:9411
  rabbitmq:
    host: ${rabbitmq.host}

server:
  port: 9000

zipkin:
  store:
    type: mem

logging:
  level:
    org.springframework.cloud: off
    org.springframework.web: off