fbi-service:
  ribbon:
    listOfServers: localhost:8082
spring:
  application:
    name: rent-service
  zipkin:
    base-url: http://192.168.99.100:9411

logging:
  level.org.springframework.cloud: DEBUG